---
- name: Check du fichier debian
  stat:
    path: /run/reboot-required
  register: debian_file
- name: Check du fichier spécifique
  stat:
    path: /tmp/need-reboot
  register: efalia_file
- name: Version courante du noyau
  command: uname -r
  register: current_kernel
- name: Version installée du noyau
  shell:
    cmd: find /boot/vmlinuz-* | sort -V | tail -n 1 | sed 's|.*vmlinuz-||'
  register: last_installed_kernel
- name: Reboot si nécessaire
  shell:
    cmd: reboot
  when: debian_file.stat.exists or efalia_file.stat.exists or current_kernel.stdout != last_installed_kernel.stdout
